// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/tenntenn/wiresample/clock"
	"github.com/tenntenn/wiresample/server"
	"github.com/tenntenn/wiresample/weather"
	"github.com/tenntenn/wiresample/weather/geo/geomock"
	"github.com/tenntenn/wiresample/weather/source/mocksrc"
)

// Injectors from inject_prod.go:

func setupProd() (*server.Server, func(), error) {
	clockClock := clock.Default()
	geoMock := &geomock.GeoMock{}
	source := &mocksrc.Source{}
	reporter := &weather.Reporter{
		Clock:  clockClock,
		Geo:    geoMock,
		Source: source,
	}
	serverServer := server.New(reporter)
	return serverServer, func() {
	}, nil
}
