// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package handler

import (
	"github.com/tenntenn/wiresample/weather"
)

// Injectors from inject_default.go:

func newDefaultHandler() (*Handler, func(), error) {
	reporter := weather.NewReporter()
	handler := &Handler{
		Reporter: reporter,
	}
	return handler, func() {
	}, nil
}
